
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name":"comédia",
    "description":"filmes que faz ri"
}


###

GET http://localhost:3000/categories/

###

DELETE http://localhost:3000/categories/e05a99df-915f-4f0e-b432-86393deef4c3

###


PUT http://localhost:3000/categories/904cf8c6-eff0-405b-8065-ed31cd97a70f
Content-Type: application/json 

{
    "name":"Romance",
    "description":"eca!"
}

###

POST  http://localhost:3000/videos
Content-Type: application/json 

{ 
  "name":"what if",
  "description":"Eu faço é rir",
  "duration":2.30,
  "category_id":"bccbe201-0011-48fc-ab47-38e11a8bcfb3"

   
}

###

GET  http://localhost:3000/videos

